# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: kustoassistant
metadata:
  template: kustoassistant@0.1.0

workflows:
  up:
    steps:
      - azd: provision
pipeline:
  provider: github

infra:
  provider: bicep
  path: infra
  module: main